version: '3'
services:
  sclmanager:
    image: sclmanager
    environment:
      - "PORT=8082"
      - "DATABASE_URL=jdbc:mysql://db:3306/scl?useSSL=false"
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=root"
      - "S3_BUCKET=scl-replays-season4-test"
      - "SHARED_SECRET=secret"
      - "FORFEIT_PASSWORD=password"
      - "WEBROOT=/static"
      - "SCL_DEBUG=true"
    ports:
      - 8082:8082
    volumes:
      - ./static:/static
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --ssl=0 --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scl
    volumes:
      - ./db_data:/var/lib/mysql
